export enum Type{
    INT,
    BOOLEAN,
    DOUBLE,
    STRING,
    CHAR,
    VOID
}

export enum TypeOperation{
    SUMA, RESTA, MULTIPLICACION, DIVISION, MENOSUNARIO,
    MAYOR, MENOR, MAYOR_IGUAL, MENOR_IGUAL, IGUAL_IGUAL, DIFERENTE,
    OR, AND, NOT, XOR,
    INCREMENTO, DECREMENTO
}